#!/system/bin/sh
BASEDIR=/sdcard/Tasker
DEX=$BASEDIR/rish_shizuku.dex

if [ -z $1 ]; then
  echo "error: no args"
  exit 1
fi

[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="rish.support"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
