#!/system/bin/sh
export RISH_APPLICATION_ID="rish.support"
if [ -z $1 ]; then
  echo "error: no args"
  exit 1
else
  sh /system/bin/app_process -Djava.class.path="/sdcard/RishSupport/rish_shizuku.dex" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
fi
