#!/system/bin/sh
BASEDIR=/data/data/%app_package
DEX=$BASEDIR/rish.dex

if [ ! -f "$DEX" ]; then
  echo "Cannot find $DEX, please check the tutorial in Shizuku app"
  exit 1
fi

[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="%app_package"
/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
